include conf/common.conf

# CRITICAL: Point to the internal eMMC, NOT the uSD card
MENDER_STORAGE_DEVICE = "/dev/mmcblk0"

# 1. Enable Mender's native U-Boot scripts and SD image builder
MENDER_FEATURES_ENABLE:append = " mender-uboot mender-image-sd"
